### ISSUE TITLE
Clarity needed on Storage Virtual Machine (SVM) limitation

### ISSUE THREAD

**Issue by rbenigno** [NetAppDocs/cloud-volumes-ontap#100]
Page: [Limitations for Cloud Volumes ONTAP 9.7 in all cloud providers](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limitations_97.html)

> **Storage Virtual Machine (SVM) limitation**
> 
> Cloud Volumes ONTAP supports one data-serving SVM and one or more SVMs used for disaster recovery.

This statement makes it unclear to me if the additional DR SVMs can actually be used for a failover, or if it is just an inaccessible copy of the data.  If the DR data cannot be accessed by clients (as in unable to add LIFs to the DR SVM) it would be helpful to explicitly state that limitation. I do realize this is inferred by the one data-serving SVM limit, but the docs still give customer's hope.

On the other hand, if DR SVMs can be setup for client access during a failover I'm not able to find out how in the documentation.

Thank you!

**Comment by netapp-bcammett** [comment]
Ryan,

Thank you for taking the time to provide your feedback. I just sent a message to our product management team to seek clarification. I'll let you know as soon as I hear back and there is clarity that I can provide around your question.

Thanks again for contacting us.

Regards,
Ben

**Comment by netapp-bcammett** [comment]
Hi Ryan,

After discussing with product management, we updated the limitation to clarify the statement: 

> Cloud Volumes ONTAP supports one data-serving SVM and one destination SVM used for disaster recovery. You can activate the destination SVM for data access if there’s an outage on the source SVM.

The page also includes links to the SVM DR preparation and recovery express guides.

Please let us know if any further clarification is required.

Thanks again for providing your feedback.

Regards,
Ben

**Comment by rbenigno** [comment]
Hi @netapp-bcammett 

Thank you for getting clarification add in!    Can you also provide a link to the doc that describes how to setup additional LIFs to serve data from that activated SVM for each of the Cloud Providers? (GCP is what I need right away for a customer).

Thank you!

**Comment by netapp-bcammett** [comment]
@rbenigno -- From what I understand, the SVM Disaster Recovery Guide should include the steps that are needed: 
https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857

@avivdeg -- Can you help provide Ryan with any additional information?

> Can you also provide a link to the doc that describes how to setup additional LIFs to serve data from that activated SVM for each of the Cloud Providers? (GCP is what I need right away for a customer).

**Comment by rbenigno** [comment]
> @avivdeg -- Can you help provide Ryan with any additional information?
> 
> > Can you also provide a link to the doc that describes how to setup additional LIFs to serve data from that activated SVM for each of the Cloud Providers? (GCP is what I need right away for a customer).

@avivdeg To clarify, Azure and GCP are the providers I can't find NetApp documentation for.  I just want to make sure what we do is "supported" by NetApp rather than assuming the standard provider steps apply.

Thank you!

**Comment by avivdeg** [comment]
All clouds are supported

**Comment by avivdeg** [comment]
On additional lifs, for some reason, it was deleted (FYI @netapp-bcammett )

the steps are to add another IP from the cloud provider to the same vNIC, and then add the ONTAP lif

**Comment by netapp-bcammett** [comment]
@avivdeg -- Are you referring to page 20 of the SVM DR _preparation_ guide?
https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856

The guide that I linked to in a previous comment is the SVM DR _recovery_ guide, which describes how to "quickly activate a destination Storage Virtual Machine (SVM) after a disaster, and then reactivate the source SVM."

Thanks,
Ben

**Comment by avivdeg** [comment]
Yes it is, thanks!
