### ISSUE TITLE
"紺碧" should be "Azure"

### ISSUE THREAD

**Issue by imasafum** [NetAppDocs/cloud-volumes-ontap#103]
Page: [Supported configurations for Cloud Volumes ONTAP 9.7 in Azure](https://docs.netapp.com/ja-jp/cloud-volumes-ontap/reference_configs_azure_97.html)

I thin miss translating about "紺碧".
It should be "Azure"

Best regards,

**Comment by netapp-bcammett** [comment]
Hi,

Thank you for providing your feedback. We'll take a look and get back to you as soon as we can.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
@akseldavis -- Do you know who can assist us with this issue?

**Comment by gabrieltokyo** [comment]
Hi @netapp-bcammett  and @akseldavis, I know who to contact for this.
Will bring you in the loop.

**Comment by netapp-bcammett** [comment]
I'm going to provide a summary of this issue and then close it:

- We fixed the issue with a command.
- The mistranslated Azure issue is isolated to the left navigation. We have added an action item to our technical roadmap to configure a glossary to globally handle these types of issues.

Thank you!
