### ISSUE TITLE
Tagging needed to improve Japanese translation

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/cloud-volumes-ontap#118]
Page: [Supported configurations for Cloud Volumes ONTAP 9.7 in GCP](https://docs.netapp.com/ja-jp/cloud-volumes-ontap/reference_configs_gcp_97.html)

At the table, "Supported machine types" don't need to be translated.

**Comment by netapp-bcammett** [comment]
@akseldavis -- should translation issues be transferred to another repository for tracking?

**Comment by akseldavis** [comment]
@gabrieltokyo, will privately share feature roadmap. This seems like it should be translated since it isn't a product name. Perhaps the default translation is incorrect?

**Comment by gabrieltokyo** [comment]
I see. That feels strange because Google Cloud interface does not translate those machine names (exception for "custom").
<img width="917" alt="image" src="https://user-images.githubusercontent.com/34706481/99678704-7630e200-2abe-11eb-86fd-bc8daff1142d.png">

After planned releases and improvements, we can come back again to this.

**Comment by akseldavis** [comment]
I understand now. I thought you meant a literal string "Supported machine types" shouldn't be translated. I agree with your sentiment given GCP screenshot. This is a public issue so let's make sure that graphic isn't confidential. Will follow up in near future.
