### ISSUE TITLE
Supported number of nodes should clarify whether it's possible to non-disruptively upgrade from a single node to HA config

### ISSUE THREAD

**Issue by kclarkr** [NetAppDocs/cloud-volumes-ontap#138]
Page: [Supported configurations for Cloud Volumes ONTAP 9.8 in AWS](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_aws_98.html)

Supported number of nodes should clarify whether it's possible to non-disruptively upgrade from a single node to HA config

**Comment by netapp-bcammett** [comment]
Hi there,

Thank you for submitting this feedback. I'm working on an update that will go out very soon. The update will include the following:

```
Cloud Volumes ONTAP is available in AWS as a single node system and as a high-availability (HA) pair of nodes for fault tolerance and nondisruptive operations.

Upgrading a single node system to an HA pair is not supported. If you want to switch between a single node system and an HA pair, then you need to deploy a new system and replicate data from the existing system to the new system.
```

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
The docs were updated yesterday to include the statement that I mentioned in my previous comment.

Thanks again for submitting this issue.
