### ISSUE TITLE
Please add support for GP2 | GP3 

### ISSUE THREAD

**Issue by ssarioglu** [NetAppDocs/cloud-volumes-ontap#140]
Page: [Supported configurations for Cloud Volumes ONTAP 9.7 in AWS](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_aws_97.html)

We need more details about GP2 and GP3 support. Thanks.

**Comment by netapp-bcammett** [comment]
Hi there!

Thank you for submitting your feedback. I was actually in the process of updating each page to clarify the General Purpose SSD support now that there is gp2 and gp3. Those updates were just published.

The AWS pages now note support for the following:

> General Purpose SSD (gp2)

gp3 is not supported at this time.

Can you please let me know whether this update addresses your feedback?

Thanks again,
Ben

**Comment by cjodev** [comment]
Hi,
Could you please mention in the official page that gp3 is not supported currently?
Regards,
Chavdar

**Comment by netapp-bcammett** [comment]
Hi Chavdar,

I updated the supported configurations page for Cloud Volumes ONTAP in AWS by adding a footnote that "gp3 SSDs are not supported."
