### ISSUE TITLE
"c5a.18xlarge" might be wrong

### ISSUE THREAD

**Issue by kmakoto-at-netapp** [NetAppDocs/cloud-volumes-ontap#142]
Page: [Supported configurations for Cloud Volumes ONTAP 9.9.0 in AWS](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_aws_990.html)

In the section "Supported compute", an instance "c5a.18xlarge" is described on the table.  However, this might be wrong because AWS doesn't offer this instance. Could you confirm it? I think that "c5a.12xlarge" might be correct.

**Comment by netapp-bcammett** [comment]
Hello,

Yes, c5a.12xlarge is correct. Thank you very much for catching that!

I updated the page to correct this error.

Thanks again for your help. It's very much appreciated.

Regards,
Ben
