### ISSUE TITLE
I can't find the instance type of c5.18xlarge when I deploy CVO on AWS.

### ISSUE THREAD

**Issue by chigusak** [NetAppDocs/cloud-volumes-ontap#150]
Page: [Supported configurations for Cloud Volumes ONTAP 9.9.0 in AWS](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_aws_990.html)

According to the section of Supported configurations, the instance type of  c5.18xlarge is supported with BYOL.
When I tried to deploy CVO on AWS from Cloud Manager, c5.18xlarge was not found in the list of instance types.
Could you please confirm if the instance type of c5.18xlarge is supported in CVO 9.9.0? If not, please fix the cloud docs.

**Comment by netapp-bcammett** [comment]
Hello,

Thank you for reaching out. I checked and I don't see c5.18xlarge for BYOL either. I do see it for PayGo Premium though. I've reached out to our development team to figure out what's happening here. I'll let you know what I find out.

Thanks,
Ben

**Comment by chigusak** [comment]
Thanks, I'm looking forward to the answer.

**Comment by netapp-bcammett** [comment]
Hi again,

There was a mistake and c5.18xlarge was missing for BYOL. The development team just added it back.

Thanks for finding this issue and reaching out!

Regards,
Ben
