### ISSUE TITLE
Expected behaviour when exceeding the licensed capacity

### ISSUE THREAD

**Issue by laagabi** [NetAppDocs/cloud-volumes-ontap#151]
Page: [Storage limits for Cloud Volumes ONTAP 9.9.0 in Azure](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limits_azure_990.html)

Could we please look into including the expected behavior when customers exceed their licensed capacity?
In the past, we saw cases where the cvo started to shut down after 14 days and came up with a restricted aggregate. If this is still the expected behavior, kindly mention it in the documentation.

Note that this could be done for all 3 cloud provider pages:
https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limits_gcp_990.html
https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limits_aws_990.html#maximum-system-capacity-by-license
https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limits_azure_990.html

**Comment by netapp-bcammett** [comment]
Hey there,

Thanks for reaching out. 

I remember having discussions about this with product management in the past. I'll rehash that conversation and see how we can update the docs.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
After discussing with the product team, I updated the following text on each Storage limits page from this:

> ### Maximum system capacity by license
> 
> The maximum system capacity for a Cloud Volumes ONTAP system is determined by its license. The maximum system capacity includes disk-based storage plus object storage used for data tiering. NetApp doesn’t support exceeding this limit.

to this:

> ### Maximum system capacity by license
> 
> The maximum system capacity for a Cloud Volumes ONTAP system is determined by its license. The maximum system capacity includes disk-based storage plus object storage used for data tiering. 
>
> NetApp doesn’t support exceeding the system capacity limit. If you reach the licensed capacity limit, Cloud Manager displays an action required message and no longer allows you to add additional disks.

To be clear, Cloud Manager doesn't shut down Cloud Volumes ONTAP when it comes to capacity license enforcement.

Please reach out if you feel that any additional changes are need.

Thanks again for your feedback.

Regards,
Ben
