### ISSUE TITLE
Notes number for the Maximum system capacity isn't correct

### ISSUE THREAD

**Issue by pablogarciaarevalo** [NetAppDocs/cloud-volumes-ontap#156]
Page: [Supported configurations for Cloud Volumes ONTAP 9.9.0 in GCP](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_gcp_990.html)

Notes number for the Maximum system capacity isn't correct. It should shows 368 TB per license **3**, instead of 368 TB per license **2**

**Comment by netapp-bcammett** [comment]
Hi Pablo,

Thank you for catching this error and submitting the feedback. I updated the footnotes to correct the error on the 9.9.0 page and the 9.8 page.

Thanks again for reaching out!

Regards,
Ben
