### ISSUE TITLE
Adding more caution for this!

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/cloud-volumes-ontap#161]
Page: [What’s new in Cloud Volumes ONTAP 9.8](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_new_98.html)

Hi,

 As per this doc, we removed support for c4, m4, and r4 instances from 9.8 onwards but we still let upgrade to continue.

pls can you add a recommendation that says

even though ONTAP upgrade to 9.8 or above is supported we strongly recommend to change the instance to a supported one and then upgrade ONTAP?

**Comment by netapp-bcammett** [comment]
Hi there,

After speaking with the program team, I confirmed that we do support c4, m4, and r4 instances with 9.8 and later. There's no issue from what I understand.

It sounds like you might be a NetApp employee? If so, could you reach out to me directly to discuss further?

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
As discussed internally, I added a note in the Release Notes that states these instance types aren't supported with new systems, but are supported with upgrades. It also states that we recommend changing to c5, m5, or r5. This statement is on the what's new page for each release, under upgrade notes.

For example: https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_new_991.html#upgrade-notes
