### ISSUE TITLE
SVM Limit in Azure

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/cloud-volumes-ontap#165]
Page: [What’s new in Cloud Volumes ONTAP 9.9.0](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_new_990.html)

Hi,

There are some confusions about SVM limit allowed in Azure CVO.

In this page https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_new_990.html#latest-update-21-apr-2021 , for Azure we had mentioned the below.

Up to 24 storage VMs (SVMs) are supported with Cloud Volumes ONTAP BYOL. Those 24 storage VMs can serve data or be configured for disaster recovery (DR).

The **previous limit in Azure was 12 storage VMs** used for DR.

However Azure had only single SVM support till ONTAP 9.8. See the references below.
From **CVO 9.8 docs.**
https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limits_azure_98.html#aggregate-limits

https://docs.netapp.com/us-en/occm/task_managing_svms_azure.html
Multiple storage VMs are supported with Cloud Volumes ONTAP BYOL in Azure with an add-on license starting with the 9.9.0 release. Go to the Cloud Volumes ONTAP Release Notes to verify the supported number of storage VMs for your version of Cloud Volumes ONTAP.

**Comment by netapp-bcammett** [comment]
Hello,

Support for 24 SVMs was introduced in 9.9.0 (that's described earlier on the same page). That included 12 SVMs for DR.

A little over a month later, the SVM DR limit was increased from 12 to 24.

I can update the page to make sure that's clear.

Thanks for submitting this feedback.

Regards,
Ben

**Comment by sabarig84** [comment]
Hi Ben,

Confusion is a reference that says 9.8 in Azure supported 12 SVMs which i guess is not true.

the 9.8 azure storage limit section says below.

One data-serving SVM and one destination SVM used for disaster recovery. You can activate the destination SVM for data access if there’s an outage on the source SVM. 1

The one data-serving SVM spans the entire Cloud Volumes ONTAP system (HA pair or single node).

**Comment by netapp-bcammett** [comment]
Since this was an update to the 9.9.0 release notes, the statement was referring to the 9.9.0 release itself:

> The previous limit in Azure was 12 storage VMs used for DR.

It wasn't meant to refer to the 9.8 release, but that wasn't 100% clear.

I've updated the release notes to make that more explicit:

> The previous limit in the 9.9.0 release was 12 storage VMs used for DR in Azure.

Thanks,
Ben
