### ISSUE TITLE
Update of the supported region map - AWS Japan-Osaka region (ap-northeast-3)

### ISSUE THREAD

**Issue by kmakoto-at-netapp** [NetAppDocs/cloud-volumes-ontap#189]
Page: [Supported configurations for Cloud Volumes ONTAP 9.10.0 in AWS](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_aws_9100.html)

It seems that AWS Japan-Osaka region (ap-northeast-3) is supported after CVO 9.9.10.
Could you check the latest status and update the supported region map?

**Comment by netapp-bcammett** [comment]
Hello,

Thank you for contacting us. I just sent a question to our product manager and the person who manages the following page:
https://cloud.netapp.com/cloud-volumes-global-regions

They'll confirm that Osaka is supported and update that page. I'll let you know when this is complete.

Thanks,
Ben

**Comment by kmakoto-at-netapp** [comment]
Hi Ben,
Thank you for your prompt action.
I look forward to your reply.

**Comment by netapp-bcammett** [comment]
Hello,

I just received confirmation that we do support the the Japan-Osaka region (ap-northeast-3) in AWS. 

Someone from the cloud team will update this page: https://cloud.netapp.com/cloud-volumes-global-regions

I will update the "what's new" section in the release notes later today with this information.

Thank you for reaching out.

Regards,
Ben

**Comment by netapp-bcammett** [comment]
The Global Regions Maps page on Cloud Central was updated to include Osaka. I also updated the "what's new" section in the Cloud Manager docs.

https://cloud.netapp.com/cloud-volumes-global-regions

Thanks again,
Ben
