### ISSUE TITLE
Update the https://cloud.netapp.com/cloud-volumes-global-regions in Japan/Osaka Region

### ISSUE THREAD

**Issue by netapptakayuki** [NetAppDocs/cloud-volumes-ontap#190]
Page: [Supported configurations for Cloud Volumes ONTAP 9.10.0 in AWS](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_aws_9100.html)

"Supported regions For AWS region support, see Cloud Volumes Global Regions."

Currently The CVO single/HA can be deployed at the Japan/Osaka region now. Would you update the Global Regions Maps ?

**Comment by netapp-bcammett** [comment]
Hello,

Thank you for contacting us. We are tracking this update through https://github.com/NetAppDocs/cloud-volumes-ontap/issues/189.

Regards,
Ben

**Comment by netapp-bcammett** [comment]
Hello,

I just received confirmation that we do support the the Japan-Osaka region (ap-northeast-3) in AWS. 

Someone from the cloud team will update this page: https://cloud.netapp.com/cloud-volumes-global-regions

I will update the "what's new" section in the release notes later today with this information.

Thank you for reaching out.

Regards,
Ben

**Comment by netapp-bcammett** [comment]
The Global Regions Maps page on Cloud Central was updated to include Osaka. I also updated the "what's new" section in the Cloud Manager docs.

https://cloud.netapp.com/cloud-volumes-global-regions

Thanks again,
Ben
