### ISSUE TITLE
cloud-volumes-ontap - new feature "TCP reset" on 9.10.1 Azure CVO HA - in CVO release notes.

### ISSUE THREAD

**Issue by anee04** [NetAppDocs/cloud-volumes-ontap#197]
Page: [What’s new in Cloud Volumes ONTAP 9.10.1](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_new_9101.html)

More update on the TCP reset feature in release notes here can help, as customer is asking for information on the alert about use of this feature, if disruptive for CVO, if enabling it on entire vNet causes issue to other VMs etc.,

 https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_new_9101.html#reduced-unplanned-failover-time

Existing KB: (updated here but new feature information in release notes is what customer expects)
https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Volumes_ONTAP_(CVO)/High_availability_mode_isn't_enabled_on_this_Azure_subscription

Customer sees the alert (to turn on High Availability ) but no documentation on this feature in Cloud docs for CM or CVO release notes.
![image](https://user-images.githubusercontent.com/64034143/150164048-bdb49518-245a-4103-818b-fccad048b57e.png)

**Comment by netapp-bcammett** [comment]
As discussed internally, I updated the text to include more details about the enhancement.
https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_new_9101.html#9-10-1-rc1-28-nov-2021

Thanks again for reaching out with your feedback.

Regards,
Ben
