### ISSUE TITLE
AWS capacity limits in 9.5 release notes

### ISSUE THREAD

**Issue by filipzahradnik** [NetAppDocs/cloud-volumes-ontap#26]
Page: [Storage limits for Cloud Volumes ONTAP 9.5](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_storage_limits_95.html)

System capacity limits only shows Azure, not AWS limit.

**Comment by netapp-bcammett** [comment]
Hi there,

Cloud Volumes ONTAP 9.5 is not yet available in AWS--it's available only in Azure. We'll add the storage limits for AWS as soon as it's released. The "What's new" page will be updated, as well.

Thank you for your feedback.

**Comment by filipzahradnik** [comment]
Ok, that makes sense. Thanks.
