### ISSUE TITLE
Clarification on Unsupported ONTAP features

### ISSUE THREAD

**Issue by definitelynotsteve** [NetAppDocs/cloud-volumes-ontap#42]
Page: [Known limitations for Cloud Volumes ONTAP 9.5](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limitations_95.html)

==
Unsupported ONTAP features
The following features are not supported with **Cloud Volumes ONTAP for AWS**:
* Aggregate-level inline deduplication
* Disk maintenance center
* Disk sanitization
* Fibre Channel (FC)
(etc)
==

Aren't these features also not supported in Azure?

Thanks,
Steve

**Comment by netapp-bcammett** [comment]
Steve,

Thank you for catching this issue and notifying us about it. I fixed it for 9.5, 9.4, and 9.3. The updated pages are now live.

Thanks again for your feedback!
