### ISSUE TITLE
RAID-DP is called out for being not supported, but so is RAID-4. 

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/cloud-volumes-ontap#52]
Page: [Limitations for Cloud Volumes ONTAP 9.6 in all cloud providers](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limitations_96.html)

I am writing an exam question that requires that you need to know that CVO doesn't support RAID-DP or RAID-4.  And I couldn't find it anywhere in the documentation.  
Really what I wanted to find was that CVO is RAID zero (RAID-0).  This is really an important thing for people using CVO to understand about fault tolerance.

**Comment by netapp-bcammett** [comment]
The Unsupported features list was updated to include the following:

- RAID4, RAID-DP, RAID-TEC (RAID0 is supported)

In addition, I updated the following page in the Cloud Manager documentation to mention the supported RAID type:
https://docs.netapp.com/us-en/occm/concept_storage.html#raid-type

Thanks again for your feedback.
