### ISSUE TITLE
Max System capacity vs Max Licensed Capacity

### ISSUE THREAD

**Issue by phoebegoh** [NetAppDocs/cloud-volumes-ontap#54]
Page: [NetApp Cloud Volumes ONTAP Release Notes](https://docs.netapp.com/us-en/cloud-volumes-ontap/index.html)

Request from SE team for clarification:
* clearly define the differences between max capacity and max licensable capacity.
* for example, where the maximum capacity for a CVO instance is the total combined EBS+S3 - the user could still assign the maximum number of disks to the AWS EC2 and potentially exceed the licensed capacity

**Comment by netapp-bcammett** [comment]
I'm a little late in updating the status of this issue. Changes were merged on Sept 6 that addressed the feedback from the SE team.

https://github.com/NetAppDocs/cloud-volumes-ontap/pull/56/files
