### ISSUE TITLE
Need max file size, more specific than dependent on volume.

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/cloud-volumes-ontap#68]
Page: [Storage limits for Cloud Volumes ONTAP 9.6 in AWS](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limits_aws_96.html)

I think this page needs a little more definition around max file size and others.
It says dependent on volume size, which says dependent on aggregate size.
So if I read this I say I can for AWS have 96TB (6 x 16TB) and in Azure 192TB (12 x 16TB)  in an aggregate, does that mean I can have a 196TB file?
Looking at ONTAP maximums document, it has 16TB as largest file size, I would imagine that is WAFL limitation so would be same for CVO.
https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limits_aws_96.html#maximum-system-capacity-by-license

**Comment by netapp-bcammett** [comment]
Thanks for the feedback. I updated the max file size to 16 TB.
