### ISSUE TITLE
I was told that HA might have some limitation in GCP.  Please investigate if true and update as necessary.

### ISSUE THREAD

**Issue by jherzfm** [NetAppDocs/cloud-volumes-ontap#71]
Page: [Known limitations for Cloud Volumes ONTAP 9.6 in GCP](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limitations_gcp_96.html)

**Comment by netapp-bcammett** [comment]
Hi there,

Thank you for taking the time to provide your feedback.

Cloud Volumes ONTAP is available in Google Cloud Platform as a single node system. An HA pair isn't offered at this time. That is mentioned on the "Supported configurations" page, but I went ahead and added it right at the top of that page to make it more noticeable.

https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_gcp_96.html

**Comment by jherzfm** [comment]
Netapp:

Thanks.

FYI, I would really like to see it resolved, as I have an immediate need and would like to use CVO in GCP.


Mark Herzfeld
Johnson Controls
Global Infrastructure Architecture Cloud Transformation

414-524-2888

"IT Infrastructure: Software and Hardware elements that Business Applications require to function"

This e-mail may contain information that is confidential, privileged or otherwise protected from disclosure.
If you are not an intended recipient of this e-mail, do not duplicate or redistribute it by any means. Please delete it and any attachments and notify the sender that you have received it in error.
Office Location: 5757 N. Green Bay Avenue, Dept X-86, Milwaukee, WI 53209

**Comment by netapp-bcammett** [comment]
Hi Mark,

If you have any product or pricing related questions, or just general feedback, our NetApp cloud experts are available through chat on [https://cloud.netapp.com](https://cloud.netapp.com). Just click the chat icon in the lower right.
