### ISSUE TITLE
Title can mislead

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/cloud-volumes-ontap#76]
Page: [What’s new in Cloud Volumes ONTAP 9.5](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_new_95.html)

This title jumps out at people:
Cloud Volumes ONTAP encryption is no longer supported in AWS
 
And even though the paragraph explains it, people have seen this heading and misinterpreted this as a broader statement.  I have had two different SEs get confused by this.

I would change this to say something like
"NetApp onboard key management no longer supported in Cloud Volumes ONTAP in AWS"

**Comment by netapp-bcammett** [comment]
Fixed. Thank you!
