### ISSUE TITLE
multi-SVM support is available via licensing now

### ISSUE THREAD

**Issue by scottharney** [NetAppDocs/cloud-volumes-ontap#83]
Page: [Limitations for Cloud Volumes ONTAP 9.7 in all cloud providers](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limitations_97.html)

in talking to CVO dev team, support for multiple SVMs on a CVO instance/HA pair is possible now and available via BYOL purchasing.

**Comment by netapp-bcammett** [comment]
Hi Scott,

Not yet at this time, but we'll update the documentation when it is.

**Comment by netapp-bcammett** [comment]
Multiple SVM support is documented for AWS. The docs will be updated for Azure and GCP once support is added there.
