### ISSUE TITLE
Can I use SnapMirror Sync with CVO ONTAP 9.7?

### ISSUE THREAD

**Issue by netapp-satyajit** [NetAppDocs/cloud-volumes-ontap#92]
Page: [Limitations for Cloud Volumes ONTAP 9.7 in all cloud providers](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limitations_97.html)

Can I use SnapMirror Sync with CVO ONTAP 9.7?

I read ONTAP 9.7 SE Presentation. Then CVO is not listed.
https://fieldportal.netapp.com/content/829436

But there is no description about this in the document.

Thanks,
Kan Itani

**Comment by netapp-bcammett** [comment]
SnapMirror Synchronous is listed in the Cloud Volumes ONTAP release notes as unsupported.
