### ISSUE TITLE
Is NFSv4 supported?

### ISSUE THREAD

**Issue by netapp-satyajit** [NetAppDocs/cloud-volumes-ontap#93]
Page: [Known limitations for Cloud Volumes ONTAP 9.7 in Azure](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limitations_azure_97.html)

In the document, there is such description.

HA limitations
The following limitations affect Cloud Volumes ONTAP HA pairs in Microsoft Azure:
NFSv4 isn’t supported. NFSv3 is supported.
HA pairs aren’t supported in some regions.

But using OCCM, we can create CVO HA pair with NFSv4. 
Is it still unsupported?

Thanks,
Kan Itani

**Comment by netapp-bcammett** [comment]
I confirmed that the documentation is correct--NFSv4 is **_not_** supported with HA pairs in Azure. You've uncovered a bug in the product. I filed a bug with the Cloud Manager team to get this corrected.

Thank you for your feedback!
