### ISSUE TITLE
Updates to AWS GovCloud Limitations

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/cloud-volumes-ontap#97]
Page: [Known limitations for Cloud Volumes ONTAP 9.7 in AWS](https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limitations_aws_97.html)

Currently this page states:

"Cloud Manager must be deployed in an AWS GovCloud (US) region if you want to launch Cloud Volumes ONTAP instances in the same AWS GovCloud (US) region."

This is confusing and suggests that separate Cloud Managers need to be deployed if you want to deploy CVO on GovCloud East and West regions.  You only need a single Cloud Manager in any GovCloud region to support CVO in any of the two GovCloud regions.  The wording on this is probably left over from when there was only a single GovCloud region.  

Suggest updating to the following:

"Cloud Manager must be deployed in an AWS GovCloud (US) region if you want to launch Cloud Volumes ONTAP instances in any AWS GovCloud (US) region."

**Comment by netapp-bcammett** [comment]
Thank you for the suggestion! I made the change exactly as you suggested.

I appreciate you taking the time to provide your feedback.

Regards,
Ben
